GPUI_KIT_REVISION: str
GPUI_VERSION: str

class Bridge:
    def __init__(self, tree_json: str) -> None: ...
    def submit(self, batch_json: str) -> None: ...
    def reconcile(self, tree_json: str, roots_json: str, batch_json: str) -> None: ...
    def snapshot(self, token: int) -> None: ...
    def next_events(self) -> str: ...
    def run(self, title: str, width: float, height: float, theme: str = "light") -> None: ...
    def notify(self, message: str, title: str = "", variant: str = "info") -> None: ...
    def close(self) -> None: ...
    def finish(self) -> None: ...
