GPUI_KIT_REVISION: str
GPUI_VERSION: str

class Bridge:
    def __init__(self, tree_json: str, config_json: str = "") -> None: ...
    def submit(self, batch_json: str) -> None: ...
    def reconcile(
        self, tree_json: str, roots_json: str, batch_json: str, config_json: str | None = None
    ) -> None: ...
    def execute(self, id: int) -> None: ...
    def snapshot(self, token: int) -> None: ...
    def set_theme(self, theme_json: str) -> None: ...
    def theme_snapshot(self, token: int) -> None: ...
    def next_events(self) -> str: ...
    def run(
        self, title: str, width: float, height: float, theme: str = "light", theme_json: str | None = None
    ) -> None: ...
    def notify(self, message: str, title: str = "", variant: str = "info") -> None: ...
    def close(self) -> None: ...
    def finish(self) -> None: ...
